# Generated by Django 5.0.2 on 2024-03-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://wmmedia.sgp1.cdn.digitaloceanspaces.com/blog.png'),
        ),
    ]
