# Generated by Django 5.0.2 on 2024-03-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
